export const OBTER_PROJETOS = 'OBTER_PROJETOS';
export const CADASTRAR_PROJETO = 'CADASTRAR_PROJETO';
export const ATUALIZAR_PROJETO = 'ATUALIZAR_PROJETO';
export const REMOVER_PROJETO = 'REMOVER_PROJETO';

export const OBTER_TAREFAS = 'OBTER_TAREFAS';
export const CADASTRAR_TAREFA = 'CADASTRAR_TAREFA';
export const ATUALIZAR_TAREFA = 'ATUALIZAR_TAREFA';
export const REMOVER_TAREFA = 'REMOVER_TAREFA';
